spring.application.name=pos

# Database connection (H2 for Local Testing)
spring.datasource.url=jdbc:h2:mem:nestely_pos_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console
spring.h2.console.enabled=true

# Hibernate ddl-auto (update for dev, validate for prod)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret config
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# Server port
server.port=8080

# Logging
logging.level.org.springframework.security=DEBUG

# Razorpay Configuration
razorpay.key.id=rzp_test_YourKeyIdHere
razorpay.key.secret=YourKeySecretHere
